name: '[CI/CD] Markdown linter'
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '!**/CHANGELOG.md'

jobs:
  md-linter:
   runs-on: ubuntu-latest
   steps:
    - name: Install markdownlint
      run: npm install -g markdownlint-cli@0.33.0
    - name: Checkout project
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Execute markdownlint
      run: |
        ls -l
      
